version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    ports:
      - '3310:3306'
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:

